Feature #13 Email notification functionality
olofeldre/DD2480-group1-assignment2 pull request #14
Opened 2021-02-11 15:15 UTC by JoakimSkoog97

Closes #13 

This commit add the email functionality. The pom file have been
updated to include the new dependencies and a file named
email.java have been created. The functionality of email.java is that it can send
emails to any email adress from a newly created email adress.

This functionality is yet to be connected to the CI server.

Co-authored-by: Robin Wänlund <robin.wanlund@hotmail.com>

2021-02-12 12:17 UTC, olofeldre requested changes

2021-02-12 12:17 UTC, olofeldre commented on CI/src/main/java/group1/email.java
> +                return new PasswordAuthentication("group1SoffaKth@gmail.com", "group1arbast!QWE");
no passwords please

2021-02-12 12:17 UTC, olofeldre commented on CI/src/main/java/group1/email.java
> +                return new PasswordAuthentication("group1SoffaKth@gmail.com", "group1arbast!QWE");
change your password, make the code read the password from a file, and add this file to the gitignore

2021-02-12 12:20 UTC, antonlovstrom requested changes

2021-02-12 12:20 UTC, antonlovstrom commented on CI/src/main/java/group1/email.java
> +    public static void main(String[] args) {
Please make this into a static function that takes a message, subject line and recipient as arguments.

2021-02-12 13:27 UTC, antonlovstrom commented on CI/src/main/java/group1/email.java
> +    public static void main(String[] args) {
And also please add tests to test the email functionality if possible.

2021-02-15 11:02 UTC, olofeldre commented
All comments have been addressed in the latest commit. Please review.

2021-02-15 12:37 UTC, CarolineLarsen requested changes
Overall, very good! I just have a small note about the test class: all tests are not commented. Only the first test is commented properly. The second test has no comments, and the comment of the third test does not really say what the purpose of the test is.

2021-02-15 16:05 UTC, CarolineLarsen commented
LGTM

2021-02-16 12:10 UTC, merged